name: ShulkerKing
version: 2.0.3
main: com.shulkerking.ShulkerKingPlugin
api-version: 1.16
author: XuViGaN
description: Open shulker boxes directly from your hand
website: https://github.com/xuvigan/shulkerking

commands:
  shulkerking:
    description: ShulkerKing main command
    usage: /<command> [reload]
    permissions:
      shulkerking.open:
        description: Allows opening shulker boxes from hand
        default: true
      shulkerking.offhand:
        description: Allows using shulker boxes in off-hand
        default: true
      shulkerking.place:
        description: Allows placing shulker boxes with Shift+RMB
        default: true
      shulkerking.admin:
        description: Access to admin commands
        default: op
      shulkerking.cooldown.vip:
        description: VIP cooldown reduction
        default: false
      shulkerking.cooldown.premium:
        description: Premium cooldown reduction
        default: false
      shulkerking.cooldown.bypass:
        description: Bypass cooldown completely
        default: false

permissions:
  shulkerking.open:
    description: Allows opening shulker boxes from hand
    default: true
  shulkerking.admin:
    description: Allows reloading plugin configuration
    default: op
  shulkerking.offhand:
    description: Allows opening shulker boxes from offhand
    default: true
